apiVersion: v1                      
kind: Service                       
metadata:                           
  name: go-svc                   
spec:                               
  selector:                         
    name: goapp                    
  ports:                            
  - port: 80                        
    name: http                      
    targetPort: 8080                  
    protocol: TCP                   
                                    
---                                 
apiVersion: apps/v1                 
kind: Deployment                    
metadata:                           
  name: go-deploy             
spec:                               
  replicas: 2                  
  selector:                         
    matchLabels:                    
      name: goapp                   
  template:                         
    metadata:                       
      labels:                       
        name: goapp               
    spec:                           
      containers:                   
      - name: go               
        image: registry.cn-hangzhou.aliyuncs.com/zgang/goappk8s:v0.6        
        imagePullPolicy: IfNotPresent
        ports:                      
        - name: http                
          containerPort: 8080
        livenessProbe:
          httpGet:
            port: http
            path: /user/1
          initialDelaySeconds: 10
          periodSeconds: 3
          timeoutSeconds: 2
          failureThreshold: 3