apiVersion: v1                      
kind: Service                       
metadata:                           
  name: go-svc2                   
spec:                               
  selector:                         
    name: goapp2                    
  ports:                            
  - port: 8001                    
    name: http2                      
    targetPort: 8080                  
    protocol: TCP                   
                                    
---                                 
apiVersion: apps/v1                 
kind: Deployment                    
metadata:                           
  name: go-deploy2             
spec:                               
  replicas: 1                 
  selector:                         
    matchLabels:                    
      name: goappgin                   
  template:                         
    metadata:                       
      labels:                       
        name: goappgin              
    spec:     
      imagePullSecrets:
      - name: aliyun-secret                      
      containers:                   
      - name: go2               
        image: registry.cn-hangzhou.aliyuncs.com/zgang/goappk8s:v0.6
        imagePullPolicy: IfNotPresent
        ports:                      
        - name: http2                
          containerPort: 8080
        volumeMounts:
        - name: go-log
          mountPath: /app/logs
      volumes:
      - name: go-log
        persistentVolumeClaim:
          claimName: go-pvc1
# kubectl create secret docker-registry aliyun-secret --docker-server=registry.cn-hangzhou.aliyuncs.com --docker-username=119098598@1888046525536031.onaliyun.com --docker-password=a12345678a --docker-email=119098598@1888046525536031.onaliyun.com